name: Windows Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Abhängigkeiten installieren
        run: |
          choco install cmake ninja visualstudio2019buildtools -y
          refreshenv

      - name: Build-Verzeichnis erstellen
        run: mkdir build

      - name: Projekt konfigurieren
        run: |
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Projekt bauen
        run: |
          cd build
          ninja
